name: rabbited
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.1+3
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - assets/gifs/  

scripts:
  build: flutter pub run build_runner build
  build_delete: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
