name: rabbited
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  optimized_cached_image: ^0.1.13
  stepper_counter_swipe: ^0.0.5
  lottie: ^0.4.0
  path_provider: ^1.6.10
  hive: ^1.4.1+1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  flutter_modular: ^1.2.5+1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/lotties/carrot.json
  - assets/lotties/bunny.json

scripts:
  build: flutter pub run build_runner build
  clean: flutter pub run build_runner clean
